{% set uhd_lib = "uhd" %}
{% set version = "4.7.0.0" %}

package:
  name: uhd
  version: {{ version }}

source:
  url: https://github.com/EttusResearch/uhd/archive/v{{ version }}.tar.gz
  sha256: afe56842587ce72d6a57535a2b15c061905f0a039abcc9d79f0106f072a00d10
  patches:
    - 0001-usrp2-Include-DSP-bit-gain-derived-from-peak-stream-.patch
    - 0002-python-Fix-libpyuhd-install_name-on-macOS.patch
    - 0003-cmake-Make-libuhd-linking-to-Python-library-PRIVATE.patch
    - 0004-cmake-Don-t-set-package_dir-in-setup.py.in.patch
    - 0005-cmake-Prefer-python-config-extension-suffix-to-hard-.patch
    - 0006-lib-types-Declare-types-used-with-digital_filter_-ba.patch

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('uhd', min_pin='x.x.x', max_pin='x.x.x') }}
  entry_points:   # [not linux]
    - rfnoc_image_builder = uhd.rfnoc_image_builder:main  # [win]
    - uhd_images_downloader = uhd.uhd_images_downloader:main  # [not linux]
    - usrpctl = uhd.usrpctl_script:main  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.5.1
    - ninja
    - pkg-config

  host:
    - libboost-devel
    - libusb
    - mako >=0.5.0
    - ncurses  # [not win]
    - numpy
    - pybind11
    - python
    - requests
    - ruamel.yaml
    - setuptools

  run:
    - mako >=0.5.0
    - ncurses  # [not win]
    - python
    - pyyaml
    - requests
    - ruamel.yaml

test:
  commands:
    # verify CLI tools
    {% set cmds = ["uhd_cal_rx_iq_balance", "uhd_cal_tx_dc_offset"] %}
    {% set cmds = cmds + ["uhd_cal_tx_iq_balance", "uhd_config_info"] %}
    {% set cmds = cmds + ["uhd_find_devices", "uhd_image_loader"] %}
    {% set cmds = cmds + ["uhd_images_downloader", "uhd_usrp_probe"] %}
    {% set cmds = cmds + ["rfnoc_image_builder", "usrpctl"] %}
    {% set cmds = cmds + ["usrp2_card_burner"] %}  # [linux]
    {% for cmd in cmds %}
    - {{ cmd }} --help || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - {{ cmd }} --help || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    {% endfor %}

    # verify libraries
    - test -f $PREFIX/lib/libuhd${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\uhd.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\uhd.lib exit 1  # [win]

    # run select commands
    - uhd_config_info --print-all
    - uhd_find_devices || (($? < 128))  # [unix]

  imports:
    - uhd

about:
  home: httsp://github.com/EttusResearch/uhd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: host/LICENSE
  summary: Software driver and API for the Ettus Research USRP SDR platform
  description: |
    UHD is the free & open-source software driver and API for the Universal
    Software Radio Peripheral (USRP(TM)) SDR platform, created and sold by
    Ettus Research. UHD supports all Ettus Research USRP(TM) hardware,
    including all motherboards and daughterboards, and the combinations thereof.
  doc_url: https://files.ettus.com/manual/
  dev_url: https://github.com/EttusResearch/uhd

extra:
  recipe-maintainers:
    - ryanvolz
