{% set version = "3.15.0.0" %}

package:
  name: uhd
  version: {{ version }}

source:
  url: https://github.com/EttusResearch/uhd/archive/v{{ version }}.tar.gz
  sha256: eed4a77d75faafff56be78985950039f8d9d1eb9fcbd58b8862e481dd49825cd
  patches:
    - 0001-usrp2-Include-DSP-bit-gain-derived-from-peak-stream-.patch
    - 0002-lib-utils-Don-t-use-hard-coded-path-constants.patch
    - 0003-python-Fix-internal-library-name-incl.-suffix-to-mat.patch
    - 0004-python-Do-not-link-against-python-lib-for-building-a.patch
    - 0005-Fix-build-RPATH-remaining-on-installed-libpyuhd-by-n.patch
    - 0006-lib-Make-sure-generated-file-is-closed-when-writing-.patch
    - 0007-boost-Include-bind.hpp-where-used-add-BOOST_BIND_GLO.patch
    - 0008-cmake-Prefer-python-confix-extension-suffix-to-hard-.patch
    - 0009-Fix-compilation-with-Boost-1.76.patch

build:
  number: 10
  run_exports:
    - {{ pin_subpackage('uhd', min_pin='x.x.x', max_pin='x.x.x') }}
  entry_points:   # [not linux]
    - uhd_images_downloader = uhd.uhd_images_downloader:main  # [not linux]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.5.1
    - jom  # [win]
    - make  # [not win]
    - pkg-config  # [not win]

  host:
    - boost-cpp
    - libusb
    - mako >=0.5.0
    - ncurses  # [not win]
    - numpy
    - pybind11
    - python
    - requests
    - setuptools

  run:
    - boost-cpp
    - ncurses  # [not win]
    - {{ pin_compatible('numpy') }}
    - python
    - requests
    - six

test:
  commands:
    # verify CLI tools
    {% set cmds = ["uhd_cal_rx_iq_balance", "uhd_cal_tx_dc_offset"] %}
    {% set cmds = cmds + ["uhd_cal_tx_iq_balance", "uhd_config_info"] %}
    {% set cmds = cmds + ["uhd_find_devices", "uhd_image_loader"] %}
    {% set cmds = cmds + ["uhd_images_downloader", "uhd_usrp_probe"] %}
    {% set cmds = cmds + ["usrp2_card_burner"] %}  # [linux]
    {% for cmd in cmds %}
    - {{ cmd }} --help || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - {{ cmd }} --help || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    {% endfor %}

    # verify libraries
    {% set uhd_lib = "uhd" %}
    - test -f $PREFIX/lib/lib{{ uhd_lib }}${SHLIB_EXT}  # [unix]

    # run select commands
    - uhd_config_info --print-all
    - uhd_find_devices || (($? < 128))  # [unix]

  imports:
    - uhd

about:
  home: httsp://github.com/EttusResearch/uhd
  license: GPL-3.0-only
  license_family: GPL
  license_file: host/LICENSE
  summary: 'Software driver and API for the Ettus Research USRP SDR platform'
  description: |
    UHD is the free & open-source software driver and API for the Universal
    Software Radio Peripheral (USRP(TM)) SDR platform, created and sold by
    Ettus Research. UHD supports all Ettus Research USRP(TM) hardware,
    including all motherboards and daughterboards, and the combinations thereof.
  doc_url: https://files.ettus.com/manual/
  dev_url: https://github.com/EttusResearch/uhd

extra:
  recipe-maintainers:
    - ryanvolz
