{% set uhd_lib = "uhd" %}
{% set version = "4.0.0.0" %}

package:
  name: uhd
  version: {{ version }}

source:
  url: https://github.com/EttusResearch/uhd/archive/v{{ version }}.tar.gz
  sha256: 4f3513c43edf0178391ed5755266864532716b8b503bcfb9a983ae6256c51b14
  patches:
    - 0001-usrp2-Include-DSP-bit-gain-derived-from-peak-stream-.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('uhd', min_pin='x.x.x', max_pin='x.x.x') }}
  # windows requires vs2015+ to build and therefore can't build against py2k
  skip: true  # [win and py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.5.1
    - jom  # [win]
    - {{ cdt('libudev-devel') }}  # [linux]
    - make  # [not win]
    - pkg-config  # [not win]

  host:
    - boost-cpp
    - libusb >=1
    - mako >=0.5.0
    - ncurses  # [not win]
    - numpy
    - python
    - requests
    - ruamel.yaml
    - setuptools

  run:
    - boost-cpp
    - ncurses  # [not win]
    - {{ pin_compatible('numpy') }}
    - python
    - pyyaml
    - requests
    - ruamel.yaml

test:
  commands:
    # verify CLI tools
    {% set cmds = ["uhd_cal_rx_iq_balance", "uhd_cal_tx_dc_offset"] %}
    {% set cmds = cmds + ["uhd_cal_tx_iq_balance", "uhd_config_info"] %}
    {% set cmds = cmds + ["uhd_find_devices", "uhd_image_loader"] %}
    {% set cmds = cmds + ["uhd_usrp_probe"] %}
    {% set cmds = cmds + ["uhd_images_downloader", "usrp2_card_burner"] %}  # [linux]
    {% for cmd in cmds %}
    - {{ cmd }} --help || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - {{ cmd }} --help || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    {% endfor %}

    # verify libraries
    {% set uhd_lib = "uhd" %}
    - test -f $PREFIX/lib/lib{{ uhd_lib }}${SHLIB_EXT}  # [unix]

    # run select commands
    - uhd_config_info --print-all
    - uhd_find_devices || (($? < 128))  # [unix]

  imports:
    - uhd

about:
  home: httsp://github.com/EttusResearch/uhd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: host/LICENSE
  summary: Software driver and API for the Ettus Research USRP SDR platform
  description: |
    UHD is the free & open-source software driver and API for the Universal
    Software Radio Peripheral (USRP(TM)) SDR platform, created and sold by
    Ettus Research. UHD supports all Ettus Research USRP(TM) hardware,
    including all motherboards and daughterboards, and the combinations thereof.
  doc_url: https://files.ettus.com/manual/
  dev_url: https://github.com/EttusResearch/uhd

extra:
  recipe-maintainers:
    - ryanvolz
