travis:
  secure:
    BINSTAR_TOKEN: l72nCsYHywSrw3i4qKPtz8GJKJTkJCSAP5MNYaq8pWJru3+dWExdWAcfTXOXbtymazd+ENx4Im3Aj3wHoI6SSzrg2RHkzhQvSv0Nm093fE0E7TxDX9AOj/zQNVZYnYecAS115emZopm1DTyRCgRmop8QheC+XRd3Bgp4T82mK2gO+UdHQ1FgGl9oEsWM68RY0xGeRfjo27/1YV1QAVdv22p5HYJC120yeLxyLZdXWohtdkdILesPUZwc52SFMebzpuEHJqmNxnMDdKMOCi3jn/WKP9NlGGKFi+WazOIjbwmKaDnqXB34gMb9OWVU2g6fK+GanSKAFe9LSZTPD5yhvNtrM+16fbQbTOYmrOtvtJPWb26Nz1fyUhiw4S3BE+7rbYTf6unY699pmXI8WpLCfvU6HW2VVfdvqypkQg1mx2G29ENvvR2IP3+g4VDjuhcSQEckLqMzZdmPNkCzOoWnulpTWZI5m9OQbweyJV6FZ0FROZx+UwiwiQ3+7c34x6y4v0quAk7+nQLUVlHgujiaFr+n6YCUpd3i2KEJ4JJTUpIpr5BZvH/Fqy22toDPRM8LLXWO7NFSFtAGfGoEyW/gMI4GnzxiSL0kgFiyp2EXMKiPtY41lToE9YohLhax4gV0tzuqGbz5Mpoybnt490CIbDlfFZxtpJ2IE8CUY//Q7eU=
conda_forge_output_validation: true
bot:
  automerge: true
