azure:
  store_build_artifacts: true
bot:
  abi_migration_branches:
  - 3.15
  automerge: true
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
