# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_numpy1.18python3.6.____cpythonpython_implcpython:
        CONFIG: linux_64_numpy1.18python3.6.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_numpy1.18python3.6.____cpy_h3afe82b383
      linux_64_numpy1.18python3.7.____cpythonpython_implcpython:
        CONFIG: linux_64_numpy1.18python3.7.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_numpy1.18python3.7.____cpy_hab6921aec9
      linux_64_numpy1.18python3.8.____cpythonpython_implcpython:
        CONFIG: linux_64_numpy1.18python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_numpy1.18python3.8.____cpy_h99c6c63bc2
      linux_64_numpy1.19python3.7.____73_pypypython_implpypy:
        CONFIG: linux_64_numpy1.19python3.7.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_numpy1.19python3.7.____73__h68dd2141d6
      linux_64_numpy1.19python3.9.____cpythonpython_implcpython:
        CONFIG: linux_64_numpy1.19python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_numpy1.19python3.9.____cpy_hf4d3df2be7
      linux_ppc64le_numpy1.18python3.6.____cpythonpython_implcpython:
        CONFIG: linux_ppc64le_numpy1.18python3.6.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_numpy1.18python3.6.___h1e680c8dc4
      linux_ppc64le_numpy1.18python3.7.____cpythonpython_implcpython:
        CONFIG: linux_ppc64le_numpy1.18python3.7.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_numpy1.18python3.7.___ha2d7781fe7
      linux_ppc64le_numpy1.18python3.8.____cpythonpython_implcpython:
        CONFIG: linux_ppc64le_numpy1.18python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_numpy1.18python3.8.___h12ab300d74
      linux_ppc64le_numpy1.19python3.7.____73_pypypython_implpypy:
        CONFIG: linux_ppc64le_numpy1.19python3.7.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_numpy1.19python3.7.___h1457821301
      linux_ppc64le_numpy1.19python3.9.____cpythonpython_implcpython:
        CONFIG: linux_ppc64le_numpy1.19python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_numpy1.19python3.9.___h373238fc7c
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
        artifact_name="conda_artifacts_$(build.BuildId)_$(SHORT_CONFIG_NAME)"
        echo "##vso[task.setVariable variable=ARTIFACT_NAME]$artifact_name"
        if [ -d build_artifacts ]; then
          echo "##vso[task.setVariable variable=CONDA_BLD_DIR_EXISTS]true"
        fi
    displayName: Check for conda build artifacts
    condition: succeededOrFailed()

  - publish: build_artifacts/
    artifact: $(ARTIFACT_NAME)
    condition: eq(variables.CONDA_BLD_DIR_EXISTS, 'true')